### ISSUE TITLE
Cherrypick AXEnhancedUserInterface workaround

### ISSUE THREAD

**Issue by LiamKearn** [rxhanson/RectanglePro-Community#129]
As the title says 🙏🏻!

**Comment by rxhanson** [comment]
I pulled this out in the latest release of Pro, but you can get it back by using the following terminal command:

`defaults write com.knollsoft.Hookshot enhancedUI -int 2`

Then restart the app.

The reason I pulled it is because it's not the best solution, and some users will still experience the issue, even with that behavior. 

Of course, the best fix is when the Chrome team decides to address it. I will likely roll in another way of dealing with it regardless, with some sort of toggle in Pro since it can affect other apps.

**Comment by LiamKearn** [comment]
Still haven't updated chromium to the latest "hack" fix, this will work well for me.

Appreciate the quick response.
