### ISSUE TITLE
License key storage

### ISSUE THREAD

**Issue by LiamKearn** [rxhanson/RectanglePro-Community#140]
Hi I'm in the practice of committing preference files to my public dotfiles.

I'm assuming `Paddle-Rectangle Pro-580977-SD` is derived from my license key or some sort of session identifier of [Paddle](https://paddle.com) so probably a secret I don't want to commit?

If so is there any way this sort of thing could be stored in keychain? Not sure on good practice with apple centric development or if this is practical 😅 I'm only suggesting this as I've seen other apps (tableplus) interface with it so I'd assume it has some sort of decent public API.

Just wanted to give thanks again, I ended up purchasing your app and I'm very happy with it, It's working excellently to combine other applications into one and make my windows tile based on % of display size!

**Comment by rxhanson** [comment]
Sorry for the delay on this one. I could add something that would automatically read a text file with your license key in it and activate your license. However, since license activation typically doesn't happen very frequently for a user, it's hard to want to dedicate time to this over other issues/features that have more impact.

**Comment by LiamKearn** [comment]
Absolutely fair, Primarily wanted to check in that this is the key. Thanks!
