### ISSUE TITLE
Feature request: Have adjacent windows adapt, when resizing windows

### ISSUE THREAD

**Issue by F1orian** [rxhanson/RectanglePro-Community#16]
Not sure how hard this is to implement, but I recall seeing this in another app.

Scenario:
1. One app snapped to the right half of the screen, and one app each snapped to the top-left, and bottom-left quarter.
2. Resize the app that is snapped to the right half with the mouse, for example making it bigger by extending it to the left.
3. Both apps on the left side should adapt and be reduced in size, to maintain the established grid

**Comment by rxhanson** [comment]
This is commonly requested. The main reason why I have avoided it is because resizing the left side of a window programmatically is nearly always really janky (as a 3rd party in macOS). If you've tried Amethyst, you might know what I mean. There are just a lot of other features that would feel more polished that I would prefer to put in the app at this time. If someone implemented it for Rectangle, as a Terminal command only setting not in the UI, then it would also make its way into Pro.

**Comment by colin715** [comment]
I bought the Pro license because I really like the feature set that currently exists, but this is the one feature that I need the most.  I recently moved from Windows to Mac and this is the one feature that I really miss.

**Comment by rxhanson** [comment]
@colin715 thanks for the support. I have been thinking that I would like to add this in, and I was going to try out only resizing the 2nd window on mouseup, rather than during the drag. Hopefully I can get to it soon.

**Comment by rxhanson** [comment]
Housekeeping closing this one out, it's in the current version.

**Comment by colin715** [comment]
I was just thinking about this a few weeks ago and had given up hope.  I am loving the new feature, thank you so much!
