### ISSUE TITLE
fn key doesn't function as a shortcut modifier

### ISSUE THREAD

**Issue by itskando** [rxhanson/RectanglePro-Community#18]
See title: fn key doesn't function as a shortcut modifier

Example: Windows Arrow Keys.

Can place fn into shortcut box, but cannot perform the action when the fn key is involved.

![image](https://user-images.githubusercontent.com/15063663/154853619-a5466ecd-6d69-48c5-bf6f-44ea37bdf81d.png)

**Comment by rxhanson** [comment]
This is a bug, in that fn shouldn't be allowed in this recorder. Fn is allowed in the quick throw recorder because it's not actually binding to keyboard shortcuts. For win arrow keys, the shortcut is attempting to bind to the modifier + arrow keys, which fails in macOS.

Currently, macOS treats the fn key differently from the rest of the modifiers, despite some changes in Monterey, and the binding of shortcuts fails because macOS doesn't allow it.

**Comment by itskando** [comment]
Damn, I'm trying to come over seamlessly from the stagnant but functional HyperDock, which allowed for fn but didn't use the 'press what you want to use' api. It was just a 'check off any combination of the 5 standard modifiers' that you want to use with the arrows, so I'm guessing he hardcoded something to get the fn to play nice based on what you said.

Thanks for the fast response.

**Comment by itskando** [comment]
Actually, for confirmation, will the fn key work with other commands and just not the 'Windows Arrow keys' shortcut because the buttons in there get added to a formula off screen whereas most hotkeys have the whole thing?

**Comment by rxhanson** [comment]
>Damn, I'm trying to come over seamlessly from the stagnant but functional HyperDock, which allowed for fn but didn't use the 'press what you want to use' api. It was just a 'check off any combination of the 5 standard modifiers' that you want to use with the arrows, so I'm guessing he hardcoded something to get the fn to play nice based on what you said.

There is at least one way around this macOS limitation: listening to keystrokes rather than registering shortcuts. There are tradeoffs for going that route, though, and I prefer to stick with conventions built into the OS.

>Actually, for confirmation, will the fn key work with other commands and just not the 'Windows Arrow keys' shortcut because the buttons in there get added to a formula off screen whereas most hotkeys have the whole thing?

Perhaps more clear: Keyboard shortcuts cannot contain the fn key, but "mod+cursor move" can. Win arrow keys is registering keyboard shortcuts. Let me know if there's still confusion there.

**Comment by itskando** [comment]
> Perhaps more clear: Keyboard shortcuts cannot contain the fn key, but "mod+cursor move" can. Win arrow keys is registering keyboard shortcuts. Let me know if there's still confusion there.

Okay, that is more clear.

I had thought you meant: Fn+Shift in the box, to be used with arrow keys in general couldn't work, but Fn+Shift+LeftArrow in the box for a specific shortcut **could** work.

The above is good to know, I'll use it.

**Comment by itskando** [comment]
This is likely outside of your purview, but for recording purposes:

fn key on laptop internal keyboard is fine.
fn key on logitech K780 wireless keyboard (connected via bluetooth or via usb wifi dongle) doesn't register the fn key in the shortcut.

**Comment by itskando** [comment]
The fault is logitech's. No issue with your software. Their fn key does nothing when pressed. It can't be swapped with Karabiner-Elements, and it forces stock shortcuts like fn + leftArrow forces Ctrl+Shift+leftArrow. Garbage design choice.

**Comment by rxhanson** [comment]
@jacksongoode I'm sorry, I don't understand what you're asking for. If you don't mind, can you open a new discussion with what you want a shortcut using fn to execute?
