### ISSUE TITLE
Gestures don't work properly in Excel

### ISSUE THREAD

**Issue by ruok5** [rxhanson/RectanglePro-Community#2]
I can only get gestures to work in Excel for Mac when starting with the cursor over the window title bar. Of course, this 100% defeats the purpose of gestures.

I've been using Hookshot since June 2021, and I could swear gestures worked in Excel at first.

The same behavior has been observed on an Intel Mac running Big Sur and on an M1 running Monterey, updated to Rectangle Pro 2.0.

**Comment by rxhanson** [comment]
Thanks for being a Hookshot user and reporting. This is actually what I am currently working on fixing. (Excel is not the only app that has this)

If it worked previously it's because Excel used to properly work with the accessibility API and now it no longer does. Sometimes restarting the problematic app (in this case Excel) will fix the issue as certain apps are just flaky with their adherence to the accessibility API.

If you're up for testing out a beta, that would definitely help. I can post back when I have something worth testing.

**Comment by rxhanson** [comment]
I skipped the beta and just went with a release. Feel free to grab the latest from within the app or at https://rectangleapp.com/pro 

Let me know how it goes!

**Comment by ruok5** [comment]
Tested on Big Sur (11.6.2) with Excel 16.56 (21121100) on an Intel Mac. I can confirm that the issue is resolved on this configuration.

**Comment by rxhanson** [comment]
Thanks for the quick test and the kind words! I'm glad that it's working smoothly now.
