### ISSUE TITLE
RectangularPro Preferences window - easily obscured

### ISSUE THREAD

**Issue by itskando** [rxhanson/RectanglePro-Community#23]
This doesn't appear in Alt+Tab or the dock.
(It does appear in HyperSwitch though..)

Since the preferences pane often leads to testing the actions being set, actions frequently obscure the preferences window. It thus becomes difficult to return to, without going to the menu bar (if it's enabled) and mousing way down. (Spotlight/Alfred isn't so bad a means, but it's less intuitive in the moment.)

Not a showstopper, but worth logging a note.

**Comment by rxhanson** [comment]
This has been brought up for my other app, Multitouch, as well. This is kind of a weird restriction that is more of a default behavior of macOS than anything else. By declaring the app as one that runs in the background, the app will not be shown in the dock. I could change the app so that when the prefs window is open, the app changes to a dock app, and back again when the prefs window closes, but it's fairly apparent that macOS devs didn't really intend it to work that way as there are some weird quirks doing it. As is my typical stance, I try to align with the intended behavior of macOS and that's why it behaves this way.

**Comment by rxhanson** [comment]
I was thinking, it wouldn't be hard to add a pin button to the UI that could just keep the window on top. Could add clutter to the UI though. Worth thinking about at least.
