### ISSUE TITLE
What is "Safe Area" and "Min Dist to Appear"?

### ISSUE THREAD

**Issue by 9mm** [rxhanson/RectanglePro-Community#325]
I'm using window throw with `rest 3 touches, remove all except 1`

This is _nearly_ perfect except i frustratingly accidentally trigger it like 5 times a day. i'm almost certain its because of my left palm grazing the track pad ...

I'm wondering if I can utilize these shortcuts to help prevent this, except I don't know what they do

**Comment by rxhanson** [comment]
You'll likely want to adjust the min dist to appear. This means you have to move the cursor farther from the initial point where you performed the gesture in order for the dot to appear.

Personally, I prefer "rest 4 touches, remove all except 1" because it's less likely to accidentally trigger.

You can think of the safe area as a circle around the dot where no window snapping footprints will be displayed/triggered.

**Comment by 9mm** [comment]
amazing, thank you. i actually had no idea the dot worked like that because safe zone was set to zero. no wonder it was so frustrating because i couldnt "undo it". this will work way better
