### ISSUE TITLE
Window Throwing with trackpad doesn't work with Telegram

### ISSUE THREAD

**Issue by F1248** [rxhanson/RectanglePro-Community#373]
MacBook Air M1 (MacBookAir10,1)
macOS 14.0 (23A344)
Rectangle Pro Version 3.0.12 (153)
Telegram 10.1.4.252330 Stable

**Comment by rxhanson** [comment]
Thanks for reporting. Unfortunately, this would be due to Telegram not responding to the Accessibility API in macOS. Typically this is resolved by restarting the app that's not working (Telegram in this case). There's not really anything that can be done from Rectangle Pro's side to make an app respond to the Accessibility API.

**Comment by jacklaing** [comment]
It seems to work if you hover the mouse over the title bar of the app.

**Comment by F1248** [comment]
> It seems to work if you hover the mouse over the title bar of the app.

Thanks for the tip! Yes, it works, even if it is very impractical.
