### ISSUE TITLE
Throw Top/Bottom Half doesn't cycle through thirds

### ISSUE THREAD

**Issue by pcherna** [rxhanson/RectanglePro-Community#493]
I have my Window Throw configured to use Left Half, Right Half, Top Half, and Bottom Half. Under General, I have Repeated commands set to "cycle 1/2, 2/3, and 1/3 on half actions". While left/right continue to work as expected, recently the Top Half and Bottom Half throws do not cycle. Instead they just become or stay at half.

![RectanglePro_Throw](https://github.com/rxhanson/RectanglePro-Community/assets/6484575/40a62112-4598-4f4a-b995-955482b77379)

![RectanglePro_General](https://github.com/rxhanson/RectanglePro-Community/assets/6484575/4b5fc9d3-81a5-4976-9863-c0b77d7caf30)

The pull down menu seems to only be showing the horizontal third options, not the vertical ones. I thought I saw them there once and then not, so maybe it's inconsistent.

![RectanglePro_Menu](https://github.com/rxhanson/RectanglePro-Community/assets/6484575/5c61acc1-e4a1-40d5-8125-7cc5f1ec6e4e)

MacOS 14.4.1 M1 Max
Rectangle Pro 3.0.22 (163)

**Comment by pcherna** [comment]
OK will do. That leaves me with two questions though...
1. Why can I still repeat on throw horizontally, but (without this change) not vertically?
2. What does the Repeated Commands setting do, if not this?

Either way, glad to have "my" behavior back :-)

**Comment by rxhanson** [comment]
> Why can I still repeat on throw horizontally, but (without this change) not vertically?

Turns out I missed the left/right halves case while making this adjustment, as my intent was to leave the across displays functionality intact. This will be adjusted in the next release.

> What does the Repeated Commands setting do, if not this?

Repeated commands is more directed toward keyboard shortcuts. 

What this boils down to is that I've actually never liked the repeated behavior with the window throw, except for in very specific scenarios (fill actions and across left/right half across displays). It's been reported as a bug to me many times, and in a number of scenarios, it feels like a bug in my usage as well. It's always hard to make changes like this, because there are a lot of users that see this functionality as a feature and have become used to it, and that's why whenever I make a change of default behavior (which is really rare) I make sure to provide a terminal flag to revert it. 

Thanks for the feedback!

**Comment by pcherna** [comment]
OK fair enough. The behavior is pretty much essential to my use of Rectangle Pro. With the terminal flag I'm fine, but if you get more feedback I suppose you might add it as a distinct Repeated Throw option. No need to do it for me, but I would endorse that.

In case it helps to understand my scenario, I use throwing -- a lot -- to set up side-by-side windows on my displays. Often that's 50/50. It's not unusual that I need more width, and then depending I might use either:
* 67/33 (or 33/67)
* 67/50 (or 50/67)
* 67/67
In the last two cases I gain extra width in the second window in exchange for some overlap. In all cases it's quick to get there with the throws.

I have one landscape monitor (for which I use side-by-side splitting), and one portrait monitor (for which I use above-below splitting).

I would say 90% of my use of Rectangle Pro is throwing, most of the rest is pushing the window to the screen edge, and a tiny bit is the menu-bar option.
