### ISSUE TITLE
How can I align the “almost maximize” window behavior to match Apple’s native version?

### ISSUE THREAD

**Issue by bigplayer-ai** [rxhanson/RectanglePro-Community#621]
How can I align the “almost maximize” window behavior to match Apple’s native version (relative position, and the same ratio)? Mine has a slight pixel offset that triggers my OCD.
![Apple's Native almost maximize](https://github.com/user-attachments/assets/aa60366d-425d-44ce-a185-6f4adf556555)

**Comment by rxhanson** [comment]
I only have maximize as an option. Do you know how I can get Apple's "almost maximize" so I can reproduce it?

![image](https://github.com/user-attachments/assets/cb0f3474-056c-42e3-8c65-c203fd0d16ea)

**Comment by bigplayer-ai** [comment]
Press alt

**Comment by rxhanson** [comment]
For me, that option is simply centering the window. Is there an almost maximize that I'm not seeing?

**Comment by bigplayer-ai** [comment]
> For me, that option is simply centering the window. Is there an almost maximize that I'm not seeing?

You’re absolutely right. However, when using the “almost maximize” feature, the window isn’t perfectly centered like Apple’s native alignment—it’s slightly misaligned by a pixel. The “almost maximize” action (which also centers the window) results in it being just a few pixels off, positioned slightly higher than Apple’s native centered alignment.

After further testing, I see that the center on rectangle pro is the problematic part, that is not the same as Apple's one... I believe almost maximize uses the logic of center?

**Comment by rxhanson** [comment]
As a quick test, I set three windows using Rectangle Pro in centered top, middle, and bottom ninths. Using Rectangle Pro's center on the middle one positioned the center window without any gaps or overlap above or below the window. Using the macOS center, it positioned it a pixel lower, which had a slight gap with the window above and some overlap with the window  below. I'm inclined to keep Rectangle Pro's centering algorithm as-is, since it is more consistent with the other positions within the app.
