### ISSUE TITLE
Feature idea: Shortcut to break browser tab out to new window

### ISSUE THREAD

**Issue by jesseko** [rxhanson/RectanglePro-Community#65]
Scenario:
In a browser with multiple tabs, hit a keyboard shortcut to pull the current tab into a new window
From there it's easy to follow up with other commands to resize, throw to a different display, etc

Don't know if this is possible, but thought worth sharing the idea.  It's one of the few places I still frequently use the mouse to manipulate windows.

At least for Chrome I don't see a built in shortcut to support this: see [Tab and window shortcuts](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ctab-and-window-shortcuts) 
Didn't check the others

**Comment by rxhanson** [comment]
Thanks for the feedback! 

This is something that I really wanted to do, but getting it right looked like it would take a lot longer than I was willing to spend on it. Looks like there would have to be some careful coordination and timing assumptions that would have to fit in place, and I think the only way to guarantee that would be to write browser plugins. I have toyed with the idea of writing browser plugins because that could give me a lot more control over other aspects, too, and it sounds fun to do. Maybe someday :)

**Comment by jesseko** [comment]
Roger that, yes, that does sound very involved, and complex to communicate the need to install more than one thing...

Just searched the chrome store and found this, which seems to do the trick
https://chrome.google.com/webstore/detail/tab-to-windowpopup-keyboa/adbkphmimfcaeonicpmamfddbbnphikh

I changed the settings to put the new window over the old one and not do any resizing.  That gets it doing what I was hoping for!
<img width="463" alt="image" src="https://user-images.githubusercontent.com/153062/169869293-b88b40f2-c19c-4253-be8f-2c755521d680.png">

Thanks for the reply and thanks for Rectangle!  Great tool!
